import '../styles/globals.css';
import Head from 'next/head';
import React from 'react';
import ApiProvider from '../src/context/Provider';

const MyApp = function ({ Component, pageProps }) {
  return (
    <ApiProvider>
      <Head>
        <title>
          Finanças
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...{ pageProps }} />
    </ApiProvider>
  );
};

export default MyApp;
